  import 'dart:typed_data';


abstract class IPictureRepoInterface {
  Future<List<Uint8List>> loadAllPictures(); //get pictures...
  Future<void> savePicture(int index, Uint8List pictureBytes); // save pictures ...
  Future<int> getMaxPictureIndex(); // get a count of all pictures ...
  Future<bool> checkConnection(); // check connection to api ...
  Future<void> login(String username, String password); // login and get a jwt token
  Future<void> handleResponse(int statusCode); // start isolate to show how an isolate works 
  Future<void> sendNotification();  // send notification to the flutter app from the api.
}
